### ISSUE TITLE
-$0.00 is being rendered in red

### ISSUE THREAD

**Issue by hannes-ucsc** [ucsc-cgp/cloud-billing-report#13]
![image](https://user-images.githubusercontent.com/5143256/87694336-e9a69980-c742-11ea-8286-0b89dc26e106.png)

The cell should be empty if the value is really between -0.01 and 0.

**Comment by natanlao** [comment]
Hannes suggests rounding up to the nearest cent.

**Comment by hannes-ucsc** [comment]
For negative values this would mean rounding down to cent.

Simply rounding is also fine. IOW, it would be ok if -0.00001 were displayed as an empty cell or as `-0.01` as long as the same rule is applied uniformly. It would be a problem if values between -0.01 and 0 were displayed as `-0.01` in one row and as an empty cell in another row.

**Comment by natanlao** [comment]
This is an edge case that is no longer applicable; for demo, show code changes.
