### ISSUE TITLE
GCP billing data feature is deprecated

### ISSUE THREAD

**Issue by natanlao** [ucsc-cgp/cloud-billing-report#25]
The [Cloud Billing export](https://cloud.google.com/billing/docs/how-to/export-data-file) feature this report script uses is now deprecated. The only supported mechanism for exporting billing data is through [export to BigQuery](https://cloud.google.com/billing/docs/how-to/export-data-bigquery).

**Comment by natanlao** [comment]
Potential approaches:
* Begin exporting billing data to BigQuery. #16 calls for loading billing CSVs into an SQL database and querying that SQL database to build a report; this approach would provide the same benefits (with better [visualization tools](https://cloud.google.com/billing/docs/how-to/visualize-data)) with less work.
* Remove GCP reporting functionality altogether. GCP has existing [billing visualization](https://cloud.google.com/billing/docs/how-to/reports) and [alerting tools](https://cloud.google.com/billing/docs/how-to/budgets).

It's also worth noting here that AWS billing data can also be exported to Athena, where it can be queried with normal SQL.

**Comment by theathorn** [comment]
@hannes-ucsc "Let's use BigQuery - need cost estimate".

**Comment by natanlao** [comment]
@hannes-ucsc See this page on [cost of use](https://cloud.google.com/billing/docs/how-to/export-data-bigquery#cost). In summary:

* Loading data is free.
* Storing data is rated (at most) at $0.020 per GB, with the first 10 GB free.
* Queries are rated (at most) at $5.00 per TB, with the first 1 TB free.

The combined size of all billing data maintained since September 20, 2017 is less than 30 MB. This feature is unlikely to incur significant cost.

**Comment by hannes-ucsc** [comment]
To be triaged for next steps.

**Comment by theathorn** [comment]
@hannes-ucsc "Natan to evaluate placing AWS report data into BigQuery tables, either in the schema that Google uses natively, or an intermediate schema".

**Comment by natanlao** [comment]
It's feasible to load AWS billing data into BigQuery (separate from GCP billing data), using a subset of the schema used for GCP billing data.

That said, I think using Amazon's Athena integration for billing data is worth considering:
* There would be a single authoritative source of AWS billing data, as opposed to maintaining and manually synchronizing a different, remote copy.
* It would let report generation be a fully read-only operation.

The caveat is that the integration cannot retroactively import data; integrating new and old data would likely have to be done separately.

**Comment by natanlao** [comment]
Hannes says single database with compatible schemas is desirable, with choice of service left to me. BigQuery makes the most sense because of aforementioned deprecation.
