### ISSUE TITLE
Clean up improperly-tagged resources

### ISSUE THREAD

**Issue by natanlao** [ucsc-cgp/cloud-billing-report#28]
Find or develop a tool that:

* Identifies untagged AWS resources
* Can delete untagged resources after a grace period

This ticket might end up not living here, but I think it's okay to track it here for now.

**Comment by natanlao** [comment]
Hannes would like a proposal before proceeding with this.

**Comment by melainalegaspi** [comment]
Spike to come up with design proposals

**Comment by natanlao** [comment]
Proposal summary
* Use cloud-custodian, a cloud management tool, to provision AWS Config rules for identifying and removing untagged AWS resources.
* Store cloud-custodian configuration in a ucsc-cgp repository so that policy changes can undergo code review. cloud-custodian can be run with GitHub Actions, Travis, GitLab, etc. on a policy change.
* The exact policy to be implemented is outside of my scope. Adam proposed a strict plan below (kill untagged or improperly tagged resources after 1h after a go-live date). Benedict expressed support for a progressively-strict policy. A reasonable policy to start with might be:
  - Warn of improperly-tagged resources more than one hour old daily.
  - Stop/suspend improperly-tagged resources after two days.
  - Remove improperly-tagged resources after three days.
  - The only required tag is `Owner`.

---

After reviewing a number of cloud management tools, cloud-custodian/cloud-custodian appears to be the most mature solution for our use case. It can act as a wrapper around AWS Config, Amazon's "native" solution for resource management, generating policies specified as YAML. There are some advantages to using cloud-custodian instead of AWS Config directly:
- cloud-custodian supports management of more resource types than AWS Config
- Management actions built in to cloud-custodian may reduce need for custom code
- Using cloud-custodian allows us to dry-run enforcement action
- Using cloud-custodian may lower the barrier to broader cost-reduction plans in the future, including application of these policies to GCP, Azure, etc.

* Multi-cloud support

For propriety, @adamnovak's proposal was

> We should institute a new policy on a particular go-live date. The
> policy will require that all resources have an Owner tag that is an
> IAM user e-mail address, possibly with a plus-separated component
> identifying a project (e.g. gitlab-ci+anovak@soe.ucsc.edu). We will
> find or develop an enforcement tool to implement this policy. As far
> as possible, we will coinfigure our AWS accounts with auto-tagging so
> that the AWS web interface wizards and tag-oblivious AWS API calls
> will by default add tags in accordance with this policy.

> As of the go-live date date, any non-conforming EC2 instance, AMI
> image, EBS volume, S3 bucket, SSH key, SimpleDB database, IAM role, or
> security group created on or after the go-live date will be deleted by
> the enforcement tool within no more than 60 minutes, but no less than
> 10 minutes (to give people time to tag manually if necessary). Owner
> tags that aren't valid e-mail addresses (e.g. "adamnovak", "vgteam",
> "gitlab-ci") will not protect objects from deletion. Already-existing
> resources will be collected into a list, and we can send the list
> around with a few progressively stronger admonishments before deleting
> them for good (by flipping a flag in the enforcement tool).

**Comment by natanlao** [comment]
From standup:
- Create a new repo under ucsc-cgp to track this work.
- This ticket should be converted to an epic. Create the epic under the new repository.
- Proceed with prototyping proposal before referring this to Benedict, Erich.
- For prototyping, acquire read-only credentials to a CGL account.

**Comment by adamnovak** [comment]
This sounds good to me.

Now that I look at it again, that +-separated bit might be backward.
We use gmail for mail, and it lets you add a *trailing* +-separated
component to an address to help you sort your incoming e-mails. I
don't think we'd have to worry about parsing the addresses at the
level of this tool.

On 11/17/20, Natan Lao <notifications@github.com> wrote:
> From standup:
> - Create a new repo under ucsc-cgp to track this work.
> - This ticket should be converted to an epic. Create the epic under the new
> repository.
> - Proceed with prototyping proposal before referring this to Benedict,
> Erich.
> - For prototyping, acquire read-only credentials to a CGL account.
>
> --
> You are receiving this because you were mentioned.
> Reply to this email directly or view it on GitHub:
> https://github.com/ucsc-cgp/cloud-billing-report/issues/28#issuecomment-729171767


-- 
Adam Novak (He/Him)
Senior Software Engineer
Computational Genomics Lab
UC Santa Cruz Genomics Institute
"Revealing life’s code."

Personal Feedback: https://forms.gle/UXZhZc123knF65Dw5

**Comment by amarjandu** [comment]
Closing this issue as https://github.com/ucsc-cgp/cgp-cloud-policies has been active to address this issue.
