### ISSUE TITLE
Anomaly in Elasticsearch Service costs on platform-hca-dev

### ISSUE THREAD

**Issue by natanlao** [ucsc-cgp/cloud-billing-report#30]
The 10 Nov 2020 report for platform-hca-dev indicates a cost of $103 for the day, but Cost Explorer says that the cost is closer to $60.

This can be reproduced by generating a report for 2020-11-10 against `s3_report_archive_path = 'ucsc_billing_report/ucsc_billing_report/20201101-20201201/4de1237a-5ead-441e-93cc-311ff2fd23bc/ucsc_billing_report-1.csv.gz'`. Notably, generating the same report against future billing data (i.e., published after `4de1237a`) results in normal usage being reported.

My guess is that this discrepancy is arising because of how costs are assigned to dates; the report assigns each cost to the beginning of each usage period, and my guess is that Cost Explorer assigns costs to the end of each usage period. This doesn't fully explain the observed behavior.

I identified similar behavior in the 10 Oct 2020 report.

**Comment by natanlao** [comment]
My guess was correct. Inspecting the billing CSVs manually, these are the costs accrued by AWS Elasticsearch Service on platform-hca-dev:

| Report date | CSV date | Cost (grouped by UsageEndDate) | Cost (grouped by UsageStartDate) |
+----+----+----+----+
| 10 Nov 2020 | 11 Nov 2020 | $102.09 | $55.48 |
| 11 Nov 2020 | 11 Nov 2020 | N/A | N/A |
| 10 Nov 2020 | 12 Nov 2020 | $46.61 | $59.38 |
| 11 Nov 2020 | 12 Nov 2020 |$59.38 |  $59.13 |

It's difficult to pinpoint exactly what happened since line items are not uniquely identified across CSVs, but it appears that 14 Elasticsearch-related line items had their UsageEndDate revised from  2020-11-10T22:00:00Z in the 11 Nov report to 2020-11-10T00:00:00Z in the 12 Nov report. If this assessment is accurate, this change would be responsible for the observed discrepancy.

The fix for this is easy: aggregate costs by UsageStartDate (which doesn't appear to change) instead of UsageEndDate.

**Comment by jessebrennan** [comment]
It seems like 17 November was another anomalous report for Elasticsearch service.
