### ISSUE TITLE
AWS reports are not generated on the first day of the month

### ISSUE THREAD

**Issue by natanlao** [ucsc-cgp/cloud-billing-report#5]
AWS reports are not generated on the first day (and sometimes even the second day) of a given month, potentially due to data not being provided by AWS. Preferably, a report should be received every day.

**Comment by natanlao** [comment]
This ticket necessitates switching from the deprecated Detailed Billing Report to the newer Cost and Usage Report. Which isn't too involved per se, but due to the architecture of the script, will require coordination with Erich and some deeper changes to how the script works. (And will probably take me some time given my growing familiarity with Perl.)

**Comment by natanlao** [comment]
@hannes-ucsc It occurs to me now that it might make sense that there is no report generated on the first day of the month. Reports seem to consistently land in S3 around 1am PT, with accruals for the previous day. On 1am PT on the first day of the month, there will have been about an hour of activity in the billing period, which would greatly reduce the utility of the report.

So, it may be the case that no report will be generated at all on 1 Aug, even with the new reporting service. I was unable to find documentation on this behavior. In any case, the work I've done to address this ticket still has value, but it ultimately might not resolve this issue.

**Comment by hannes-ucsc** [comment]
To summarize discussion about this during stand-up:

@natanlao to wait for month to roll over and observe report generation with new detailed billing report service. We'll reconvene if the desired behaviour cannot be achieved with the new billing report.

The desired behaviour is that every calendar day we get an email reporting the charges incurred on the preceding calendar day. A calendar day is defined as lasting from midnight to midnight. This implies that on August 1 we get an email about charges incurred on July 31. The totals on that email should reflect all charges incurred during July. The email sent out on August 2 should cover August 1 only and the totals on that email should be equal to the corresponding daily values. An acceptable degradation is to send out no email on Aug 1 and two emails on Aug 2, one for Jul 31 and one for Aug 1.

**Comment by natanlao** [comment]
Progress so far:
* Switched from AWS DBR to CUR. This switch did not fix the issue per se as anticipated, but it:
   - Allowed for regeneration of previous reports to help with troubleshooting
   - Demonstrated the release timeline for reports (which led to the next solution)
   - Needed to be done anyway as CUR is deprecated
* S3 information indicated that billing data was made available at the end of the day (9p PT) at the beginning of the reporting period, but not at the time we ran it (6a PT):
    ```
    2020-08-01 20:41:18     278497 ucsc_billing_report/ucsc_billing_report/20200801-20200901/dfa72c67-3bdd-4601-91a8-faf7ce876565/ucsc_billing_report-1.csv.gz
    2020-08-01 20:42:23      13311 ucsc_billing_report/ucsc_billing_report/20200801-20200901/dfa72c67-3bdd-4601-91a8-faf7ce876565/ucsc_billing_report-Manifest.json
    ```
* The proposed solution was to configure the reporting script to fail gracefully on the first day of the month if billing data was not available, and to configure an extra cron job that runs the reporting script at 10pm PT only on the first day of the month.
* On 1 September, billing data was not presented by AWS. Billing data for September only became available starting on 3 September:

    ```
    2020-09-03 14:51:08    3503364 ucsc_billing_report/ucsc_billing_report/20200901-20201001/69847ecf-137a-47a0-b661-18017767d66f/ucsc_billing_report-1.csv.gz
    2020-09-03 14:53:37      13393 ucsc_billing_report/ucsc_billing_report/20200901-20201001/69847ecf-137a-47a0-b661-18017767d66f/ucsc_billing_report-Manifest.json
    2020-09-04 02:50:59    3647810 ucsc_billing_report/ucsc_billing_report/20200901-20201001/bf1fb3f6-a04c-4061-a7f7-4170d660d66e/ucsc_billing_report-1.csv.gz
    2020-09-04 03:06:15      13393 ucsc_billing_report/ucsc_billing_report/20200901-20201001/bf1fb3f6-a04c-4061-a7f7-4170d660d66e/ucsc_billing_report-Manifest.json
    ```
* AWS uploaded billing data on September 1 but categorized it in the August billing period. This occurred last month as well and appears to be normal. I found that this data is inconsistent with current-month spend.
* I am looking for a new solution.
