### ISSUE TITLE
GCP Report Does Not Provide Accurate Daily Storage Costs

### ISSUE THREAD

**Issue by juklucas** [ucsc-cgp/cloud-billing-report#56]
It looks like the GCP email report is improperly logging some storage day-of costs. Totals for the month look more accurate (but I have not verified this).

An illustrative example of the problem can be seen in the human-pangenome-ucsc project for the first ten days of October 2021. The first seven days have no value for daily storage costs, but the monthly storage cost increases steadily over that period. October 8th does show a daily storage total, but it is 1/100th of the expected daily cost.

**Comment by Richard-Hansen** [comment]
Looks like the issue was related to querying only a partial of the current month, rather than the whole. There was a similar issue for the AWS billing front as well, so this rather large PR addresses both: https://github.com/ucsc-cgp/cloud-billing-report/pull/57.
